# Generated by Django 5.1.3 on 2024-12-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/img/fotosCorredores/')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor_clp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(max_length=300)),
                ('habitaciones', models.IntegerField()),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banos', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/img/fotoCasas/')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='main.corredor')),
            ],
        ),
    ]
