# Generated by Django 5.1.3 on 2024-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/img/fotosCorredores/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/img/fotoCasas/'),
        ),
    ]
