# Generated by Django 5.1.3 on 2024-12-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_corredor_imagen_alter_propiedad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], default='venta', max_length=10),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/fotosCorredores/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='corredor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.corredor'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(upload_to='img/fotoCasas/'),
        ),
    ]
